### ISSUE TITLE
It is recommended to add the optimized system_settings.ini configuration and feedback a small BUG!

### ISSUE THREAD

**Issue by Aeuko** [Team-Neptune/DeepSea#12]
I used Ksomos before, now I use DeepSea, but system_settings.ini uses the default atmosphere, which causes a lot of troubles, such as cheating all turned on by default, which makes the experience unfriendly.

In addition, there is a small BUG I want to give feedback, which existed during the Kosmos period. In cfw-sysnand, fs/loader can not be effective, resulting in cfw-sysnand unable to run tinfoil, the solution is to add loader.kip, but these will not happen in emuMMC.

You must have cfw-sysnand and emuMMC, if you only have one cfw-sysnand, this BUG will not trigger!

Thank you for your timely presence, and thank you for your work!

**Comment by Slluxx** [comment]
For cheating, you can use Edizon, it works perfectly fine. We are using the the same settings Atmosphére ships with so you would need to enable that anyway - which doesnt make it unfriendly but rather an annoyence on your end. We will look into Atmosphére cheating at a later point.

If you have problems with Tinfoil, thats most likely because Blawar made the personal desicion to block fss0 booting. We do not support Tinfoil/Piracy and we will not try to "fix" it.
