### ISSUE TITLE
Sigpatches problem

### ISSUE THREAD

**Issue by neikxd** [Team-Neptune/DeepSea#75]
The hekate_ipl.ini lacks of extra configuration: `kip1patch=nosigchk`

This gives sigpatches problem and can't start the game, such as "error 2155-8007", "corrupted data",...

More discussion here: https://www.reddit.com/r/SwitchPirates/comments/q2kxvd/fix_sigpatches_problem_when_booting_with_hekate

**Comment by hax4dazy** [comment]
We don't provide sigpatches.

**Comment by jebediah2** [comment]
> We don't provide sigpatches.

Nevertheless his comment and explanation on Reddit are super useful to DeepSea users. I was pulling my hair out until I read this fix.

**Comment by hax4dazy** [comment]
Directly ripped from our [discord server](https://invite.teamneptune.net/):

`Sigpatches are used to start any kind of software that a user installs to their console,
this includes game-backups (or more likely, illegal game-copies) & homebrew-forwarders.
Since piracy is the main driver to use these patches, we will not provide any information other than this message.

Note: Installing anything to your home-menu is considered piracy in nintendo's eyes and will always result in a ban.
Uninstalling will not help.`

**Comment by jebediah2** [comment]
We got your point. That doesn't change the fact that his comment is extremely useful when people do what you don't support doing even though your package is designed to use sigpatches as a (likely) option. It's just silly to respond you don't provide sigpatches when someone helps other fix the package you do provide once they collected sigpatches on their own. Or are you just talking to the FBI to make sure you don't provide sigpatches?

**Comment by hax4dazy** [comment]
Did you read the message I sent above? It specifically states that `Since piracy is the main driver to use these patches, we will not provide any information other than this message.` Also, Nintendo themselves have taken down several GitHub repositories which contained sigpatches. We do not want to have our entire project deleted just because we included sigpatches. 

Also please keep in mind that our AiO CFW pack is not meant for piracy. The installer we have included is mainly used for installing backup. We have also banned any and all piracy talk from our discord server.

I am going to lock this issue as we do not support sigpatches and that will stay that way.
