### ISSUE TITLE
Uninstall

### ISSUE THREAD

**Issue by Bongkopfraucher** [Team-Neptune/DeepSea#91]
Hello Team-Neptune! 
Do you know how I can uninstall DeepSea?

**Comment by Slluxx** [comment]
Why do you want to uninstall it?
Since its just atmosphere with extra homebrews and settings, you cant really uninstall deepsea. you can however just remove the switch, atmosphere and bootloader folder and that would remove anything which comes from deepsea (but most likely also things you added yourself/the system added for you).
